`NON GRADE CHALLENGE 5`

---

- Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

In [7]:
import numpy as np
from numpy import array
from numpy.linalg import det
from numpy.linalg import eig,inv
a = np.array([[[23,50],[7,12]],
            [[57,67],[99,43]],
            [[72,21],[57,12]],
            [[87,26],[18,84]]])
print(a)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[72 21]
  [57 12]]

 [[87 26]
  [18 84]]]


- Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

In [3]:
b =array([
            [23,50,19],
            [7,12, 109],
            [57, 67, 98]
])
c= array ([ 17, 22, 19])

print ('hasil perkalian kedua matriks : ', b@c)

hasil perkalian kedua matriks :  [1852 2454 4305]


- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$

In [21]:
transpose_B = b.T
print('Hasil dari transpose matrix b : \n\n ',transpose_B  ,'\n\n')

det_B = np.linalg.det(b)
print('Hasil determinant dari \n\n' ,det_B, '\n\n')

inv_B = inv(b)
print('Hasil inverse dari \n\n' ,inv_B, '\n\n')

Hasil dari transpose matrix b : 

  [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]] 


Hasil determinant dari 

 131344.0000000002 


Hasil inverse dari 

 [[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]] 


